
spring:
    datasource:
#        data: classpath:/sql/data.sql
        driver-class-name: org.h2.Driver
        platform: h2
        url: jdbc:h2:file:~/family-budget
        username: sa
        password:
        schema: classpath:/sql/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
        