CREATE SEQUENCE IF NOT EXISTS user_seq;
CREATE TABLE IF NOT EXISTS "user"(
	"id" INTEGER NOT NULL DEFAULT NEXTVAL ('user_seq'),
	"email" CHARACTER VARYING(100) NOT NULL,
	"password" CHARACTER VARYING(200) NOT NULL,
	PRIMARY KEY ("id")
);