--CREATE DATABASE IF NOT EXISTS "family-budget"
--    WITH 
--    OWNER = postgres
--    ENCODING = 'UTF8'
--    LC_COLLATE = 'Portuguese_Brazil.1252'
--    LC_CTYPE = 'Portuguese_Brazil.1252'
--    TABLESPACE = pg_default
--    CONNECTION LIMIT = -1;

CREATE SEQUENCE IF NOT EXISTS  user_seq;
CREATE TABLE IF NOT EXISTS "user"(
	"id" INTEGER NOT NULL DEFAULT NEXTVAL ('user_seq'),
	"name" CHARACTER VARYING(200) NOT NULL,
	"email" CHARACTER VARYING(100) NOT NULL,
	"password" CHARACTER VARYING(200) NOT NULL,
	PRIMARY KEY ("id")
);

CREATE SEQUENCE IF NOT EXISTS income_seq;
CREATE TABLE IF NOT EXISTS "income"(
	"id" INTEGER NOT NULL DEFAULT NEXTVAL ('income_seq'),
	"name" CHARACTER VARYING(200) NOT NULL,
	"value" NUMERIC (10,2) NOT NULL, 
	"eventual_income" BOOLEAN NOT NULL,
	PRIMARY KEY ("id")
);

